mod compat;

use crate::SHADER;
use base64::{engine::general_purpose, Engine};
use std::fmt::{Display, Formatter};

#[derive(Debug, serde::Deserialize)]
pub enum InvalidSettingsImportError {
    /// Invalid format of the settings string.
    InvalidFormat,
    /// The settings string was generated by an unsupported version.
    /// (All previous versions are currently supported, so currently this should only happen
    /// when trying to import a string from a newer version).
    VersionMismatch,
    /// The base64 portion of the settings string is not valid base64.
    InvalidBase64,
    /// The settings struct could not be deserialised from the base64-encoded bytes.
    DeserialisationFailed,
}

impl InvalidSettingsImportError {
    fn to_str(&self) -> &str {
        match self {
            InvalidSettingsImportError::InvalidFormat => "Invalid settings string format",
            InvalidSettingsImportError::VersionMismatch => "Version mismatch or invalid format",
            InvalidSettingsImportError::InvalidBase64 => "Base64 decoding failed",
            InvalidSettingsImportError::DeserialisationFailed => "Deserialising data failed",
        }
    }
}

impl Display for InvalidSettingsImportError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.to_str())
    }
}

impl std::error::Error for InvalidSettingsImportError {
    fn description(&self) -> &str {
        self.to_str()
    }
}

/// Get the major and minor version number of the program in the format "major.minor".
/// This is used in exported settings strings to identify which version the string came from
/// (and therefore how it should be decoded).
fn get_major_minor_version() -> String {
    let mut version_iterator = env!("CARGO_PKG_VERSION").split('.');
    format!(
        "{}.{}",
        version_iterator.next().unwrap(),
        version_iterator.next().unwrap()
    )
}

/// The portion of the settings that are injected into the shader.
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct CustomShaderData {
    /// The expression for the iterative function that defines the fractal.
    pub(crate) equation: String,
    /// The expression that generates the colour of each pixel based on the iterations.
    pub(crate) colour: String,
    /// Arbitrary additional code to be included in the shader.
    pub(crate) additional: String,
}

impl CustomShaderData {
    /// Return the full shader with these custom parameters inserted.
    pub(crate) fn shader(&self) -> String {
        SHADER
            .replace("REPLACE_FRACTAL_EQN", &self.equation)
            .replace("REPLACE_COLOR", &self.colour)
            + &self.additional
    }
}

/// All of the settings that can be controlled in the settings window.
#[derive(Clone, serde::Serialize, serde::Deserialize)]
pub(crate) struct UserSettings {
    /// Zoom factor (1.0 zoom is defined to fit the full Mandelbrot set exactly, i.e. a range of 4 on the shortest axis).
    pub(crate) zoom: f32,
    /// Centre of the image in complex coordinates.
    pub(crate) centre: [f32; 2],
    /// Maximum number of iterations before giving up and assuming the iteration is not divergent.
    pub(crate) iterations: i32,
    /// Julia set mode (fixes c and varies the initial value of z).
    pub(crate) julia_set: bool,
    /// Colour smoothening option for the Mandelbrot set.
    pub(crate) smoothen: bool,
    /// Whether to always colour the inside (non-divergent) regions black, or to just use the colour expression.
    pub(crate) internal_black: bool,
    /// Initial value of `z`, or in Julia set mode the fixed value of `c`.
    pub(crate) initial_value: [f32; 2],
    /// Maximum magnitude of the iteration before it is considered divergent.
    pub(crate) escape_threshold: f32,
    /// Whether to add `c` to the initial value of `z` (for the Mandelbrot set this saves one iteration).
    pub(crate) initial_c: bool,
    /// Expressions to be included in the shader (this includes the iterative expression itself, and the colour generation).
    pub(crate) shader_data: CustomShaderData,
}

impl UserSettings {
    /// Export the settings to a string.
    ///
    /// The string is in the format "<MAJOR>.<MINOR>;<base64 encoded settings>".
    pub(crate) fn export_string(&self) -> String {
        let encoded =
            bincode_next::serde::encode_to_vec(self, bincode_next::config::standard()).unwrap();
        format!(
            "{};{}",
            get_major_minor_version(),
            general_purpose::STANDARD.encode(encoded)
        )
    }

    /// Decode settings from base64.
    ///
    /// The `legacy` option controls whether to use bincode 1.x (legacy) or 2.x (standard)
    /// encoding (used by versions 2.1 and 2.2 of this program respectively; previous versions
    /// are handled in the [compat] module).
    fn import_base64(base64: &str, legacy: bool) -> Result<Self, InvalidSettingsImportError> {
        let bytes = general_purpose::STANDARD
            .decode(base64)
            .map_err(|_| InvalidSettingsImportError::InvalidBase64)?;
        let result = if legacy {
            bincode_next::serde::decode_from_slice::<Self, _>(
                bytes.as_slice(),
                bincode_next::config::legacy(),
            )
        } else {
            bincode_next::serde::decode_from_slice::<Self, _>(
                bytes.as_slice(),
                bincode_next::config::standard(),
            )
        }
        .map_err(|_| InvalidSettingsImportError::DeserialisationFailed)?
        .0;
        Ok(result)
    }

    /// Decode settings from a string.
    ///
    /// This supports either a settings string, or a full shared URL with a settings string
    /// in the query parameters.
    pub(crate) fn import_string(string: &str) -> Result<Self, InvalidSettingsImportError> {
        let string = match url::Url::parse(string) {
            Ok(url) => url.query().unwrap_or_default().to_string(),
            Err(_) => string.to_string(),
        };

        if string.is_empty() {
            return Err(InvalidSettingsImportError::InvalidFormat);
        }

        let mut iterator = string.split(';');

        let major_minor_version = iterator
            .next()
            .ok_or(InvalidSettingsImportError::InvalidFormat)?;

        let base64 = iterator
            .next()
            .ok_or(InvalidSettingsImportError::InvalidFormat)?;

        let this_ver = get_major_minor_version();
        match major_minor_version {
            s if s == this_ver => Ok(UserSettings::import_base64(base64, false)?),
            "2.1" => Ok(UserSettings::import_base64(base64, true)?),
            "2.0" => Ok(compat::v2_0::UserSettings::import_base64(base64)?.into()),
            "0.5" => Ok(compat::v0_5::UserSettings::import_base64(base64)?.into()),
            "0.3" => Ok(compat::v0_3::UserSettings::import_base64(base64)?.into()),
            "0.4" => Ok(compat::v0_4::UserSettings::import_base64(base64)?.into()),
            _ => Err(InvalidSettingsImportError::VersionMismatch),
        }
    }
}

impl Default for CustomShaderData {
    /// Default shader parameters (Mandelbrot set, standard rainbow colouring, no other custom code).
    fn default() -> Self {
        Self {
            equation: "csquare(z) + c".to_string(),
            colour: "hsv_rgb(vec3(log(n + 1.0) / log(f32(uniforms.iterations) + 1.0), 0.8, 0.8))"
                .to_string(),
            additional: String::new(),
        }
    }
}

impl Default for UserSettings {
    fn default() -> Self {
        Self {
            zoom: 1.0,
            centre: [0.0, 0.0],
            iterations: 100,
            julia_set: false,
            smoothen: false,
            internal_black: true,
            initial_value: [0.0, 0.0],
            escape_threshold: 2.0,
            initial_c: false,
            shader_data: Default::default(),
        }
    }
}
